### ISSUE TITLE
Snow generation along biomes is jarring

### ISSUE THREAD

**Issue by Abershnick** [TerraForged/tracker#177] opened 2022-01-21 21:19 UTC
Not sure why it's generating like this. Maybe I touched the wrong settings in the world gen, any known fix?

![2022-01-21_15 13 57](https://user-images.githubusercontent.com/78277811/150601490-232bcbf2-dad3-4b77-a395-2ea04a104a74.png)
![2022-01-21_15 15 26](https://user-images.githubusercontent.com/78277811/150601495-a7afae71-1ec0-4837-ada7-ba24f3c60c5c.png)
![2022-01-21_14 45 34](https://user-images.githubusercontent.com/78277811/150601497-fb07905a-3e00-406f-b2c7-c4201ff7cbee.png)

**Comment by Won-Ton** [comment] 2022-01-22 08:05
Duplicate of #159

**Closed as completed by Won-Ton** 2022-01-22 08:05 UTC
Labels: duplicate, 1.16.x
