### ISSUE TITLE
Server ignoring TerraForged generation

### ISSUE THREAD

**Issue by Austjonez** [TerraForged/tracker#84] opened 2021-03-17 21:50 UTC
I have a single-player world that recently we uploaded to a server. I used TerraForged to generate a huge area initially in single-player and wanted to continue to use it on the server (I generated the world in 1.16.4 and the server is now 1.16.5). I followed the instructions and set the "level-type=terraforged" but it is still not recognizing it as a TerraForged world. Any new tree or terrain generation is still the vanilla default. note: after changing level-type=terraforged, I returned to the server properties and it changed it to "level-type=terraforged\:terraforged". I do have the same version of TerraForged running on the server and on my computer and I do have a few other mods but nothing that affects terrain generation.

**Comment by Won-Ton** [comment] 2021-03-17 22:27
When the world already exists forge reads the level-type from the world save-data so it doesn't matter what is set in the server.properties file.

If you started the server at any point without TF being present then minecraft will reset the level data to vanilla defaults and from that point onwards new chunks will always generate with vanilla generation, regardless of whether terraforged is present.

If you're certain that that^ didn't happen, then it sounds like 1.16.5 forge has issues reading the 1.16.4 world data (although that sounds unlikely). You could test this by creating a new TF world on 1.16.5 singleplayer and transferring that to the server to see if it loads correctly and new chunks generate seamlessly, and then compare with a fresh 1.16.4 TF world to see if you get different results.

TerraForged has nothing to do with how worlds are loaded on single player or on servers so any solutions (to whatever the issue is) are out of our hands. You might have better luck following the wiki guide in full and let the server create the TerraForged world from scratch rather than uploading a single player world. I appreciate that's a little annoying given you'ved pregen'd a load of chunks but it's out of our control

**Comment by Won-Ton** [comment] 2021-03-17 22:34
+ Just to clarify:

"terraforged:terraforged" is the 'full' name of our level-type but for convenience we allow you to just type in "terraforged" and then through some magic we convert it to the full name for you. It's normal working behaviour and unrelated to the issue you described.

**Comment by Austjonez** [comment] 2021-03-17 22:34
Gotcha. There was definitely a time when the server was running without TerraForged installed so that solves that. Is there any way I can go into the level data using an NBTexplorer to change it back to a TerraForge world?

**Comment by Won-Ton** [comment] 2021-03-17 22:38
If you have the save on your client still, you should just be able to copy the `level.dat` file from the client save folder to the server world save folder.

If you don't have the original world any more, but know the world seed and exact settings that you used, then you could create a new world with those seed+settings and, again, copy the level.dat from that newly created world to the server.

**Comment by Austjonez** [comment] 2021-03-17 22:40
I still have the original save on file but we have been playing on the server for a bit now. I imagine copying over the level.dat would override everything we've made, right?

**Comment by Won-Ton** [comment] 2021-03-17 22:48
No it should be fine, the level.dat only holds some of the settings and metadata about the world. The chunk/block/entity/player data is stored in in various other files within the save folder.

The world-time would get reset which might reset some of the mob difficulty. You'd need to rerun any gamerules commands that you might've been using and whatnot, but builds and progression would be otherwise unaffected.

You probably want to make a backup to be sure first though.

**Comment by Austjonez** [comment] 2021-03-17 22:49
That sounds great. Thanks for your help

**Closed** 2021-03-17 23:15 UTC
Labels: 1.16.x, not a bug
